# Generated by Django 3.2.19 on 2023-06-08 14:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 9, 14, 47, 54, 289615, tzinfo=utc), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 4, 14, 47, 54, 289621, tzinfo=utc)))]),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 9, 14, 47, 54, 289642, tzinfo=utc), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 4, 14, 47, 54, 289645, tzinfo=utc)))]),
        ),
    ]
