# Generated by Django 3.2.19 on 2023-06-09 11:28

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_task', '0006_auto_20230609_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 10, 11, 28, 22, 893706, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 5, 11, 28, 22, 893716, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 10, 11, 28, 22, 893734, tzinfo=utc), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 5, 11, 28, 22, 893737, tzinfo=utc)))]),
        ),
    ]
