# Generated by Django 3.2.19 on 2023-06-10 11:01

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_task', '0010_auto_20230609_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 11, 11, 1, 0, 344971, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 6, 11, 1, 0, 344985, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 11, 11, 1, 0, 345034, tzinfo=utc)), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 6, 11, 1, 0, 345043, tzinfo=utc))]),
        ),
    ]
