# Generated by Django 3.2.19 on 2023-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_task', '0011_auto_20230610_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customtask',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
