# Generated by Django 3.2.19 on 2023-06-07 11:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_of_holiday', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 8, 11, 31, 40, 126838, tzinfo=utc), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 3, 11, 31, 40, 126857, tzinfo=utc)))])),
                ('completed_state', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clothes', models.BooleanField(default=False)),
                ('passport', models.BooleanField(default=False)),
                ('holiday_insurance', models.BooleanField(default=False)),
                ('suitcases_packed', models.BooleanField(default=False)),
                ('holiday_paid_in_full', models.BooleanField(default=False)),
                ('car_hire', models.BooleanField(default=False)),
                ('tickets', models.BooleanField(default=False)),
                ('entertainment', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_holiday'],
            },
        ),
    ]
