# Generated by Django 3.2.19 on 2023-06-08 11:25

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0004_auto_20230607_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date_of_holiday',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 6, 9, 11, 25, 58, 90023, tzinfo=utc), django.core.validators.MaxValueValidator(datetime.datetime(2026, 3, 4, 11, 25, 58, 90043, tzinfo=utc)))]),
        ),
    ]
